steps:
  #build docker container
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}", "."]
  #push container to container registry
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"]
  #deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "."
    args:
      - "run"
      - "deploy"
      - "${_IMAGE_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
      - "--region"
      - "us-east4"
      - "--platform"
      - "managed"
      - "--service-account"
      - "${_CLOUD_RUN_SA}"
      - "PROJECT_ID=$PROJECT_ID"
      - "--min-instances"
      - "1"
images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: simple-cr-app
  _CLOUD_RUN_SA: terraform-gke@vishnu-scrum-team-new.iam.gserviceaccount.com
