steps:
  #build docker container
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}", "."]
  #push container to container registry
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"]
  #deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "."
    args:
      - "run"
      - "deploy"
      - "${_IMAGE_NAME}"
      - "--image"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"
      - "--region"
      - "us-east4"
      - "--platform"
      - "managed"
      - "--no-allow-unauthenticated"
      - "--service-account"
      - "${_CLOUD_RUN_SA}"
      - "--min-instances"
      - "1"
      - "--port"
      - "8080"
images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: backend-service
  _CLOUD_RUN_SA: 572195608405-compute@developer.gserviceaccount.com
  _PROJECT_ID: vishnu-scrum-team-new
  
