steps:
  #build docker container
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}", "."]
  #push container to container registry
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"]
  #deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "."
    args:
      - "run"
      - "deploy"
      - "${_IMAGE_NAME}"
      - "--image"
      - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "${_CLOUD_RUN_SA}"
      - "--min-instances"
      - "1"
      - "--port"
      - "9004"
images:
  - "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: cr-demo-frontend
  _CLOUD_RUN_SA: cr-demo-frontend@ashwani-21apr-22-scrumteam.iam.gserviceaccount.com
  _PROJECT_ID: ashwani-21apr-22-scrumteam
  
